# Build, but do not deploy, the book on all branches except `master`.

name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Material for MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the book
        run: |
          mkdocs build
